authApp/urls.py
from django.urls import path
from authApp import views

app_name = 'auth'
urlpatterns = [
    path('signin/', views.AccountCreateView.as_view(), name='signIn'),
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('<int:pk>', views.AccountView.as_view(), name='account'),
    path('deleteUser/', views.deleteUser, name='deleteUser'),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('account/', include('authApp.urls')),


]

blogapp/urls.py
from django.urls import path

from blogapp import views

app_name = 'main'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('allPosts/', views.AllPostsView.as_view(), name='allPosts'),
    path('postDetail/<int:pk>', views.PostDetailView.as_view(), name='postDetail'),
    path('postCreate/', views.PostCreateView.as_view(), name='postCreate'),
]

authApp/models.py
from django.db import models

# Create your models here.

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=50)
    dateCreated = models.DateField(editable=False, default=now)
    lastModifiedDate = models.DateField(null=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='blog')
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    text = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(
        User, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    blog = models.ForeignKey(
        Blog, related_name='comments', on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    datePublished = models.DateTimeField(default=now)

authApp/forms.py
from django import forms
from django.contrib.auth.models import User


class SignInForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", 'password', 'first_name', 'last_name')

blogapp/forms.py
from django import forms

from blogapp.models import Blog


class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'text']

authApp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import DetailView, FormView

from authApp.forms import SignInForm
# Create your views here.


class LoginPageView(LoginView):
    template_name = 'authApp/login.html'


def logoutUser(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:home'))


class AccountView(DetailView):
    model = User
    template_name = 'authApp/userDetail.html'
    context_object_name = 'user'


class AccountCreateView(FormView):
    form_class = SignInForm
    success_url = '/'
    template_name = "authApp/signIn.html"

    def form_valid(self, form):
        data = form.cleaned_data
        username = data['username']
        first_name = data['first_name']
        last_name = data['last_name']
        password = data['password']
        newUser = User.objects.create_user(
            username=username, first_name=first_name, last_name=last_name, password=password)
        newUser.save()

        login(self.request, newUser)
        return super().form_valid(form)


@login_required
def deleteUser(request):
    request.user.delete()
    return HttpResponseRedirect(reverse('auth:login'))

blogapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from blogapp.models import Blog, Comment
from blogapp.forms import BlogCreateForm
# Create your views here.


class HomeView(LoginRequiredMixin, ListView):
    login_url = '/account/login/'
    model = Blog

    template_name = 'blogapp/index.html'
    context_object_name = 'blogs'
    ordering = ['-dateCreated', '-id']

    def get_queryset(self):
        querySet = super().get_queryset()
        return querySet[:10]


class AllPostsView(LoginRequiredMixin, ListView):
    login_url = '/account/login/'
    model = Blog

    template_name = 'blogapp/allPosts.html'
    context_object_name = 'blogs'
    ordering = ['-dateCreated', '-id']


class PostDetailView(LoginRequiredMixin, DetailView):
    login_url = '/account/login/'
    model = Blog

    template_name = 'blogapp/postDetail.html'
    context_object_name = 'blog'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        blog = self.get_object()
        user = self.request.user
        hasLiked = blog.likes.filter(username=user.username).exists()
        context['likedByMe'] = hasLiked
        return context

    def post(self, request, pk):
        blog = Blog.objects.get(pk=pk)
        user = request.user

        if 'likePost' in request.POST:
            if user in blog.likes.all():
                blog.likes.remove(user)
            else:
                blog.likes.add(user)
            blog.save()

        else:
            comment = request.POST['comment']
            newComment = Comment(comment=comment, blog=blog, user=user)
            newComment.save()

        return HttpResponseRedirect(reverse('main:postDetail', args=[pk]))


class PostCreateView(LoginRequiredMixin, CreateView):
    form_class = BlogCreateForm
    template_name = 'blogapp/createPost.html'

    def get_success_url(self):
        id = self.request.user.id
        return reverse('auth:account', args=[id])

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

authApp/templates/authApp/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block cssFiles %}
<link rel="stylesheet" href={% static 'authApp/login.css' %}>
{% endblock cssFiles %}

{% block content %}

<div class="formContainer">
  <h1>Login</h1>
  <form action="{% url "auth:login"  %}" method='POST'>
    {% csrf_token %}
    <div class="errors">
      {% for type,error in form.errors.items %}
      {{error}}
      {% endfor %}
    </div>
    <label for="username">
      {{form.username.label}}
    </label>
    {{form.username}}
    <label for="password">
      {{form.password.label}}
    </label>
    {{form.password}}

    <button type="submit">Log in</button>
  </form>
  <p class='signInPara'>New to this blog app <a href="{% url 'auth:signIn' %}">Sign up here.</a></p>

</div>


{% endblock content %}
  

authApp/templates/authApp/signIn.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Sign In{% endblock title %}

{% block cssFiles %}
<link rel="stylesheet" href={% static 'authApp/signIn.css' %}>
{% endblock cssFiles %}

{% block content %}

<div class="formContainer">
  <h1>Sign In</h1>
  <form action="{% url 'auth:signIn' %}" method="post">
    {% csrf_token %}
    <div class="form">
      <div class="errors">
        
        {% for type,error in form.errors.items %}
        {{error}}
        {% endfor %}
      </div>
      <div class="fields">
        {{form.username.label}}
        {{form.username}}
        {{form.first_name.label}}
        {{form.first_name}}
        {{form.last_name.label}}
        {{form.last_name}}
        {{form.password.label}}
        {{form.password}}
        <button type="submit">Create Account</button>
      </div>
    </div>
  </form>
  <p class='logInPara'>Aleardy have account <a href="{% url 'auth:login' %}">Log in here.</a></p>
</div>


{% endblock content %}
  

authApp/templates/authApp/userDetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{user.get_full_name}}{% endblock title %}

{% block cssFiles %} 
<link rel="stylesheet" href={% static 'authApp/userDetail.css' %}>
{% endblock cssFiles %}


{% block content %}

<div class="information">
  <h1>Information</h1>
  <table>
    <tr>
      <td>Username</td>
      <td>{{user.get_username}}</td>
    </tr>
    <tr>
      <td>Full Name</td>
      <td>{{user.get_full_name}}</td>
    </tr>
    <tr>
      <td>Number of Posts</td>
      <td>{{user.blog.count}}</td>
    </tr>
  </table>
  <button><a href="{% url 'auth:deleteUser' %}">Delete Account</a></button>
</div>

<div class="likedPosts">
  <h1>Liked Posts</h1>
  {% if user.likes.all|length > 0   %}
  <div class="postsContainer">
      {% for blog in user.likes.all %}
        {% include 'includes/postContainer.html' %}
      {% endfor %}
    </div>
    {% else %}
      <h3>You don't have any liked post</h3>
    {% endif %}
</div>

<div class="posts">
  <h1>Your Posts</h1>
  {% if user.blog.all|length > 0 %}
        {% for blog in user.blog.all %}
          {% include 'includes/postContainer.html' %}
        {% endfor %}

  {% else %}
  <h3>You don't have any posts</h3>
  {% endif %}

  {% if user.id == request.user.id %}
  <button class='createPost'> <a href="{% url "main:postCreate" %}">Add a post</a></button>
  {% endif %}
</div>



{% endblock content %}

blogapp/templates/blogapp/allPosts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}All-Posts{% endblock title %}

{% block cssFiles %}
<link rel="stylesheet" href={% static 'blogapp/style.css' %}>
{% endblock cssFiles %}


{% block content %}

<div class="container">
  <h1>All Posts</h1>
  <div class="postsContainer">
    {% for blog in blogs %} 
    {% include 'includes/postContainer.html'%}
        {% endfor %}
  </div>
</div>
    
{% endblock content %}

blogapp/templates/blogapp/createPost.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Creat Post{% endblock title %}

{% block cssFiles %}
<link rel="stylesheet" href={% static 'blogapp/createPost.css' %}>
{% endblock cssFiles %}

{% block content %}

<h1>Create Post</h1>

<form action="#" method="post">
  {% csrf_token %}

  <div class="create">
    <label for="title">
      {{form.title.label}}
    </label>
    {{form.title}}
    <label for="text">
      {{form.text.label}}
    </label>
    {{form.text}}
  </div>
  <div class="buttons">
    <button type='button'><a href="{% url 'auth:account' user.id %}">Cancel</a></button>
    <button type="submit">Post</button>
  </div>
  </form>

{% endblock content %}

blogapp/templates/blogapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome To Blog{% endblock title %}

{% block cssFiles %}
<link rel="stylesheet" href={% static 'blogapp/style.css' %}>
{% endblock cssFiles %}


{% block content %}

<div class="container">
  <h1>Latest Posts</h1>
  <div class="postsContainer">
    {% for blog in blogs %} 
    {% include 'includes/postContainer.html'%}
        {% endfor %}
  </div>
</div>
    
{% endblock content %}

blogapp/templates/blogapp/postDetail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

{{blog.title}} 

{%endblock title %} 

{% block cssFiles %}
<link rel="stylesheet" href="{% static 'blogapp/postDetail.css' %}" />

{% endblock cssFiles %}

{% block content %}
<div class="container">
  <h1>{{blog.title}}</h1>
  <div class="details">
    <p>{{blog.dateCreated}}</p>
    <p class="author">Author : {{blog.author.get_full_name}}</p>
  </div>
  <hr />
  <div class="content">{{blog.text|linebreaks}}</div>
  <hr>
  <div class="moreInfo">
    <p class="likes">{{blog.likes.count}} Likes</p>
    <p class='lastEdited'>
      {% if blog.lastModifiedDate %}
      Last Edited : {{blog.lastModifiedDate}}
      {% else %}
      Last Edited : {{blog.dateCreated}}
      {% endif %}
    </p>
  </div>
  <div class='like'>
    <form action="#" method="post">
      {% csrf_token %}
      <input type="hidden" name="postId" value = {{blog.id}}>
      <input type="hidden" name="likePost">
      <button type="submit">
        {% if likedByMe == True %}
        <i class="fa fa-heart heart-active"></i>
        {% else %}
        <i class="fa fa-solid fa-heart"></i>
        {% endif %}
      </button>
    </form>
  </div>
</div>

<div class="container">
  <h1>Comments</h1>
  {% for comment in blog.comments.all %}
  <div class="comment">
    <p class='content'>
      {{comment.comment}}
    </p>
  </div>
  {% endfor %}
  <div class="addComment">
    <form action="{% url 'main:postDetail' blog.id %}" method="post">
      {% csrf_token %}
      <input type="text" name="comment" id="comment">
      <button type="submit">Add Comment</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    {% block cssFiles %}{% endblock cssFiles %}
    <link rel="stylesheet" href="{% static 'basestyle.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  <body>
    <nav>
      <a href="{% url 'main:home' %}">
        <div class="welcome">Welcome, To Blog</div>
      </a>
      <div class="actions">
        <a href="{% url 'main:allPosts' %}">All Posts</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'auth:account' request.user.id %}">Account</a>
        {% else %}
        <a href="{% url 'auth:login'  %}">Account</a>
        {% endif %}
        <a href="{% url 'auth:logout' %}">Log out</a>
      </div>
    </nav>
    {% block content %}{% endblock content %}
  </body>
</html>

templates/includes/postContainer.html
<a href="{% url 'main:postDetail' blog.id %}" class="postContainerLink">
  <div class="postContainer">
    <div>
      <h3>{{blog.title}}</h3>
      <p>{{blog.author.get_full_name}}</p>
    </div>
    <p>{{blog.text}}</p>
  </div>
</a>